import { readFile } from "node:fs/promises"
import { parse } from "csv-parse/sync"
import { randomUUID } from "node:crypto"
import { dirname, resolve } from "node:path"
import { fileURLToPath } from "node:url"
import type { Organization } from "../types/organization.js"

function parseNumber(value: string): number {
  const cleaned = value.trim()
  if (!cleaned) return 0
  const parsed = Number.parseFloat(cleaned)
  return Number.isNaN(parsed) ? 0 : parsed
}

function parseNullableNumber(value: string): number | null {
  const cleaned = value.trim()
  if (!cleaned) return null
  const parsed = Number.parseFloat(cleaned)
  return Number.isNaN(parsed) ? null : parsed
}

function seedStewardshipFields(score: number, label = "Preliminary 0*") {
  return {
    preliminaryStewardshipScore: score,
    verifiedStewardshipScore: null,
    objectiveStewardshipScore: score,
    personalizedStewardshipScore: score,
    stewardshipScore: score,
    stewardshipScoreLabel: label,
  }
}

export async function loadSeedOrganizationsFromCsv(): Promise<Organization[]> {
  const currentDirectory = dirname(fileURLToPath(import.meta.url))
  const csvPath = resolve(currentDirectory, "..", "..", "..", "data", "Jody_Organizations_ranked.csv")
  const csvContent = await readFile(csvPath, "utf-8")
  const records = parse(csvContent, {
    columns: true,
    skip_empty_lines: true,
  }) as Record<string, string>[]

  return records.map((record) => ({
    id: randomUUID(),
    organizationName: record["Organization Name"]?.trim() ?? "",
    category: record["Category"]?.trim() ?? "",
    subcategory: record["Subcategory"]?.trim() ?? "",
    approximateAnnualDonation: parseNumber(record["Approx Annual Donation"] ?? "0"),
    donations: [],
    address: {
      street: "",
      city: "",
      state: "",
      postalCode: "",
      country: "US",
    },
    website: "",
    ein: "",
    is501c3Verified: "",
    charityNavigatorRating: null,
    charityNavigatorProfileUrl: "",
    charityNavigatorAlert: "",
    charityWatchGrade: null,
    aceRecommendation: null,
    programPercent: null,
    fundraisingPercent: null,
    adminPercent: null,
    duplicateMission: "",
    duplicateMissionGroup: "",
    manualOverlapGroupKey: "",
    manualOverlapGroupLabel: "",
    duplicateMissionRole: "",
    notes: "",
    lastRefreshedAt: null,
    sourceMeta: {},
    researchStatus: "not_started",
    researchAttempts: 0,
    researchErrors: [],
    rankingStatus: "Not Researched",
    ...seedStewardshipFields(parseNumber(record["Legacy Fit Score"] ?? "0")),
    donorConfidenceAdjustment: 0,
    donorConfidenceReason: "No donor history signal applied.",
    objectiveRank: 0,
    personalizedRank: 0,
    globalObjectiveRank: 0,
    globalPersonalizedRank: 0,
    listObjectiveRank: 0,
    listPersonalizedRank: 0,
    rankingListSize: 0,
    rankShift: 0,
    rankShiftReason: "No personalized adjustment was applied.",
    legalVerificationStatus: "Insufficient Data",
    missionFitScore: 70,
    impactEvidenceLevel: "Not comparable / insufficient evidence",
    financialCompletenessStatus: "missing",
    watchdogReviewRequired: false,
    advocacyReviewStatus: "not_reviewed" as const,
    rankingModelVersion: "stewardship-v1",
    impactEvidenceScore: 0,
    accountabilityScore: parseNumber(record["Transparency Score"] ?? "0"),
    financialEfficiencyScore: parseNumber(record["Efficiency Score"] ?? "0"),
    financialEfficiencyStatus: "unknown",
    governanceScore: 0,
    politicalRiskScore: 0,
    confidenceScore: parseNumber(record["Confidence Score"] ?? "0"),
    confidenceBand: "Low",
    scoreBand: "Insufficient Data",
    organizationSize: "unknown",
    identityVerified: false,
    financialsVerified: false,
    impactDocumented: false,
    politicalReviewed: false,
    recommendation: "Review Before Donating",
    donationAmountAssessment: "No assessment yet. Run research to generate guidance.",
    suggestedDonationAction: "Preliminary research only — finish core fields before treating list rank as final.",
    suggestedDonationLevel: "Research First",
    legacyEligible: false,
    legacyTier: "Not Legacy Eligible",
    legacyRationale: "Legacy criteria are not yet met.",
    legacyExclusionReason: "Does not meet legacy gates yet.",
    missionBucket: "Other",
    rankingListKey: "",
    rankingListLabel: "Other",
    compactGivingRole: "Watchlist",
    politicalInvolvementNotes: "",
    impactEvidenceNotes: "",
    accountabilityNotes: "",
    checkPayeeName: "",
    donationMailingAddressLine1: "",
    donationMailingAddressLine2: "",
    donationMailingCity: "",
    donationMailingState: "",
    donationMailingZip: "",
    donationMailingCountry: "",
    advisorExportNotes: "",
    impactSourceTier: "none",
    quantifiedOutcomeCount: 0,
    impactDataYear: null,
    redFlags: [],
    nextAction: "Confirm core fields: website, ein, is501c3Verified",
    criticalMissingFields: ["website", "ein", "is501c3Verified"],
    strongestNextResearchStep: "Find EIN",
    scoreBreakdown: {
      ...seedStewardshipFields(parseNumber(record["Legacy Fit Score"] ?? "0")),
      donorConfidenceAdjustment: 0,
      donorConfidenceReason: "No donor history signal applied.",
      rankShiftReason: "No personalized adjustment was applied.",
      rankingStatus: "Not Researched",
      legalVerificationStatus: "Insufficient Data",
      missionFitScore: 70,
      impactEvidenceLevel: "Not comparable / insufficient evidence",
      financialCompletenessStatus: "missing",
      watchdogReviewRequired: false,
      advocacyReviewStatus: "not_reviewed" as const,
      rankingModelVersion: "stewardship-v1",
      impactEvidenceScore: 0,
      accountabilityScore: parseNumber(record["Transparency Score"] ?? "0"),
      financialEfficiencyScore: parseNumber(record["Efficiency Score"] ?? "0"),
      financialEfficiencyStatus: "unknown",
      governanceScore: 0,
      politicalRiskScore: 0,
      confidenceScore: parseNumber(record["Confidence Score"] ?? "0"),
      confidenceBand: "Low",
      scoreBand: "Insufficient Data",
      organizationSize: "unknown",
      identityVerified: false,
      financialsVerified: false,
      impactDocumented: false,
      politicalReviewed: false,
      recommendation: "Review Before Donating",
      donationAmountAssessment: "No assessment yet. Run research to generate guidance.",
      suggestedDonationAction: "Preliminary research only — finish core fields before treating list rank as final.",
      suggestedDonationLevel: "Research First",
      legacyEligible: false,
      legacyTier: "Not Legacy Eligible",
      legacyRationale: "Legacy criteria are not yet met.",
      legacyExclusionReason: "Does not meet legacy gates yet.",
      missionBucket: "Other",
      rankingListKey: "",
      rankingListLabel: "Other",
      compactGivingRole: "Watchlist",
      politicalInvolvementNotes: "",
      impactEvidenceNotes: "",
      accountabilityNotes: "",
      redFlags: [],
      nextAction: "Confirm core fields: website, EIN, is501c3Verified",
      criticalMissingFields: ["website", "ein", "is501c3Verified"],
      strongestNextResearchStep: "Find EIN",
      reasons: [],
      missingFields: (record["Missing Fields"] ?? "")
        .split(",")
        .map((item) => item.trim())
        .filter(Boolean),
    },
  }))
}

export function createOrganizationFromInput(input: Partial<Organization>): Organization {
  const ein = input.ein?.trim() ?? ""
  const website = input.website?.trim() ?? ""
  const category = input.category?.trim() || "Needs classification"
  const criticalMissingFields = [
    ...(website ? [] : ["website"]),
    ...(ein ? [] : ["ein"]),
    "is501c3Verified",
  ]
  const strongestNextResearchStep = ein ? (website ? "Find Form 990" : "Confirm website") : "Find EIN"

  return {
    id: randomUUID(),
    organizationName: input.organizationName?.trim() ?? "",
    category,
    subcategory: input.subcategory?.trim() ?? "",
    approximateAnnualDonation: input.approximateAnnualDonation ?? 0,
    donations: input.donations ?? [],
    address: input.address ?? {
      street: "",
      city: "",
      state: "",
      postalCode: "",
      country: "US",
    },
    website,
    ein,
    is501c3Verified: input.is501c3Verified?.trim() ?? "",
    charityNavigatorRating: input.charityNavigatorRating ?? null,
    charityNavigatorProfileUrl: input.charityNavigatorProfileUrl?.trim() ?? "",
    charityNavigatorAlert: input.charityNavigatorAlert?.trim() ?? "",
    charityWatchGrade: input.charityWatchGrade ?? null,
    aceRecommendation: input.aceRecommendation ?? null,
    programPercent: input.programPercent ?? null,
    fundraisingPercent: input.fundraisingPercent ?? null,
    adminPercent: input.adminPercent ?? null,
    duplicateMission: input.duplicateMission?.trim() ?? "",
    duplicateMissionGroup: input.duplicateMissionGroup?.trim() ?? "",
    manualOverlapGroupKey: input.manualOverlapGroupKey?.trim() ?? "",
    manualOverlapGroupLabel: input.manualOverlapGroupLabel?.trim() ?? "",
    duplicateMissionRole: input.duplicateMissionRole ?? "",
    notes: input.notes?.trim() ?? "",
    lastRefreshedAt: null,
    sourceMeta: {},
    researchStatus: "not_started",
    researchAttempts: 0,
    researchErrors: [],
    rankingStatus: "Not Researched",
    ...seedStewardshipFields(0),
    donorConfidenceAdjustment: 0,
    donorConfidenceReason: "No donor history signal applied.",
    objectiveRank: 0,
    personalizedRank: 0,
    globalObjectiveRank: 0,
    globalPersonalizedRank: 0,
    listObjectiveRank: 0,
    listPersonalizedRank: 0,
    rankingListSize: 0,
    rankShift: 0,
    rankShiftReason: "No personalized adjustment was applied.",
    legalVerificationStatus: "Insufficient Data",
    missionFitScore: 70,
    impactEvidenceLevel: "Not comparable / insufficient evidence",
    financialCompletenessStatus: "missing",
    watchdogReviewRequired: false,
    advocacyReviewStatus: "not_reviewed" as const,
    rankingModelVersion: "stewardship-v1",
    impactEvidenceScore: 0,
    accountabilityScore: 0,
    financialEfficiencyScore: null,
    financialEfficiencyStatus: "unknown",
    governanceScore: 0,
    politicalRiskScore: 0,
    confidenceScore: 0,
    confidenceBand: "Low",
    scoreBand: "Insufficient Data",
    organizationSize: "unknown",
    identityVerified: false,
    financialsVerified: false,
    impactDocumented: false,
    politicalReviewed: false,
    recommendation: "Review Before Donating",
    donationAmountAssessment: "No assessment yet. Run research to generate guidance.",
    suggestedDonationAction: "Preliminary research only — finish core fields before treating list rank as final.",
    suggestedDonationLevel: "Research First",
    legacyEligible: false,
    legacyTier: "Not Legacy Eligible",
    legacyRationale: "Legacy criteria are not yet met.",
    legacyExclusionReason: "Does not meet legacy gates yet.",
    missionBucket: "Other",
    rankingListKey: "",
    rankingListLabel: "Other",
    compactGivingRole: "Watchlist",
    politicalInvolvementNotes: "",
    impactEvidenceNotes: "",
    accountabilityNotes: "",
    checkPayeeName: "",
    donationMailingAddressLine1: "",
    donationMailingAddressLine2: "",
    donationMailingCity: "",
    donationMailingState: "",
    donationMailingZip: "",
    donationMailingCountry: "",
    advisorExportNotes: "",
    impactSourceTier: "none",
    quantifiedOutcomeCount: 0,
    impactDataYear: null,
    redFlags: [],
    nextAction: criticalMissingFields.length > 0 ? `Confirm core fields: ${criticalMissingFields.join(", ")}` : "Run research to enrich data.",
    criticalMissingFields,
    strongestNextResearchStep,
    scoreBreakdown: {
      ...seedStewardshipFields(0),
      donorConfidenceAdjustment: 0,
      donorConfidenceReason: "No donor history signal applied.",
      rankShiftReason: "No personalized adjustment was applied.",
      rankingStatus: "Not Researched",
      legalVerificationStatus: "Insufficient Data",
      missionFitScore: 70,
      impactEvidenceLevel: "Not comparable / insufficient evidence",
      financialCompletenessStatus: "missing",
      watchdogReviewRequired: false,
      advocacyReviewStatus: "not_reviewed" as const,
      rankingModelVersion: "stewardship-v1",
      impactEvidenceScore: 0,
      impactSourceTier: "none",
      quantifiedOutcomeCount: 0,
      impactDataYear: null,
      accountabilityScore: 0,
      financialEfficiencyScore: null,
      financialEfficiencyStatus: "unknown",
      governanceScore: 0,
      politicalRiskScore: 0,
      confidenceScore: 0,
      confidenceBand: "Low",
      scoreBand: "Insufficient Data",
      organizationSize: "unknown",
      identityVerified: false,
      financialsVerified: false,
      impactDocumented: false,
      politicalReviewed: false,
      recommendation: "Review Before Donating",
      donationAmountAssessment: "No assessment yet. Run research to generate guidance.",
      suggestedDonationAction: "Preliminary research only — finish core fields before treating list rank as final.",
      suggestedDonationLevel: "Research First",
      legacyEligible: false,
      legacyTier: "Not Legacy Eligible",
      legacyRationale: "Not legacy eligible yet — needs more research.",
      legacyExclusionReason: "Does not meet legacy gates yet.",
      missionBucket: "Other",
      rankingListKey: "",
      rankingListLabel: "Other",
      compactGivingRole: "Watchlist",
      politicalInvolvementNotes: "",
      impactEvidenceNotes: "",
      accountabilityNotes: "",
      redFlags: [],
      nextAction: criticalMissingFields.length > 0 ? `Confirm core fields: ${criticalMissingFields.join(", ")}` : "Run research to enrich data.",
      criticalMissingFields,
      strongestNextResearchStep,
      reasons: [],
      missingFields: [...criticalMissingFields, "programPercent", "fundraisingPercent", "adminPercent", "charityNavigatorRating"],
    },
  }
}

export function coerceOrganizationPatch(input: Partial<Organization>): Partial<Organization> {
  return {
    organizationName: input.organizationName?.trim(),
    category: input.category?.trim(),
    subcategory: input.subcategory?.trim(),
    approximateAnnualDonation: input.approximateAnnualDonation,
    website: input.website?.trim(),
    ein: input.ein?.trim(),
    is501c3Verified: input.is501c3Verified?.trim(),
    charityNavigatorRating: input.charityNavigatorRating ?? undefined,
    programPercent: parseNullableNumber(String(input.programPercent ?? "")),
    fundraisingPercent: parseNullableNumber(String(input.fundraisingPercent ?? "")),
    adminPercent: parseNullableNumber(String(input.adminPercent ?? "")),
    duplicateMission: input.duplicateMission?.trim(),
    notes: input.notes?.trim(),
  }
}
